version: '3'
services:
  web:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - node_modules:/app/node_modules
      - ./:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://speedypoll@postgres/speedypoll
  postgres:
    image: postgres:9.6.2-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: speedypoll
      POSTGRES_DB: speedypolls
      POSTGRES_PASSWORD: 33Km4V81!
volumes:
  node_modules:
